"""empty message

Revision ID: 1a496fa9088d
Revises: 58287615cd58
Create Date: 2021-02-16 14:01:27.917238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a496fa9088d'
down_revision = '58287615cd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture', 'grades')
    op.drop_column('lecture', 'opened_grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('opened_grade', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lecture', sa.Column('grades', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
