"""empty message

Revision ID: 478b0763e33b
Revises: a6d7e590f3a6
Create Date: 2021-02-16 23:24:58.262993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478b0763e33b'
down_revision = 'a6d7e590f3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_student', sa.Column('grade', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_student', 'grade')
    # ### end Alembic commands ###
