"""empty message

Revision ID: 5f1e441337ea
Revises: 1a496fa9088d
Create Date: 2021-02-16 16:35:59.812065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f1e441337ea'
down_revision = '1a496fa9088d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_time',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lecture', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['lecture'], ['lecture.id'], name='lecture_time_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
