"""empty message

Revision ID: a6d7e590f3a6
Revises: 5f1e441337ea
Create Date: 2021-02-16 16:37:18.904209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d7e590f3a6'
down_revision = '5f1e441337ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('full_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture', 'full_name')
    # ### end Alembic commands ###
